import { createCipheriv, createDecipheriv, hkdfSync, randomBytes } from "node:crypto";
import type { OrgIntegrationCredential } from "@shared/schema";

/**
 * Encryption at rest for a hospital's own integration credentials.
 *
 *   key        INTEGRATION_KEY env: 64 hex chars (used as the 32-byte key), or
 *              any secret of 32+ characters (32 bytes derived with
 *              HKDF-SHA256, fixed salt + info below). Render generates one
 *              (render.yaml generateValue); on AWS it is an SSM SecureString.
 *   cipher     AES-256-GCM, a fresh 96-bit IV per write, 128-bit tag.
 *   AAD        "docturn-integration:<orgId>:<integrationId>:v<keyVersion>" —
 *              a ciphertext copied into another tenant's row fails to decrypt.
 *
 * No key → storage is DISABLED (credentialKeyState().ok === false) and the
 * routes refuse to save anything: credentials are never stored in plaintext.
 * Nothing here logs; callers never log what it returns.
 */

export const CREDENTIAL_KEY_VERSION = 1;
const HKDF_SALT = "docturn/integration-credentials";
const HKDF_INFO = "aes-256-gcm/v1";

export type CredentialKeyState =
  | { ok: true; key: Buffer; source: "hex" | "hkdf" }
  | { ok: false; reason: "missing" | "too_short"; message: string };

export const KEY_MISSING_MESSAGE =
  "Saving hospital credentials is disabled: the DocTurn operator has not set INTEGRATION_KEY on the server " +
  "(Render: Environment → INTEGRATION_KEY, generated by render.yaml; AWS: SSM SecureString /docturn/prod/INTEGRATION_KEY, " +
  "then fetch-env-from-ssm.sh and a restart). Nothing is ever stored in plaintext.";

export function credentialKeyState(env: NodeJS.ProcessEnv = process.env): CredentialKeyState {
  const raw = (env.INTEGRATION_KEY ?? "").trim();
  if (!raw) return { ok: false, reason: "missing", message: KEY_MISSING_MESSAGE };
  if (/^[0-9a-f]{64}$/i.test(raw)) return { ok: true, key: Buffer.from(raw, "hex"), source: "hex" };
  if (raw.length >= 32) {
    const key = Buffer.from(hkdfSync("sha256", Buffer.from(raw, "utf8"), HKDF_SALT, HKDF_INFO, 32));
    return { ok: true, key, source: "hkdf" };
  }
  return {
    ok: false,
    reason: "too_short",
    message:
      "Saving hospital credentials is disabled: INTEGRATION_KEY must be 64 hex characters or a secret of at least 32 characters " +
      "(generate one with `openssl rand -hex 32`).",
  };
}

function aad(orgId: number, integrationId: string, version: number): Buffer {
  return Buffer.from(`docturn-integration:${orgId}:${integrationId}:v${version}`, "utf8");
}

export interface SealedCredentials {
  ciphertext: string;
  iv: string;
  authTag: string;
  keyVersion: number;
}

/** Encrypt a credential object for one org + integration. Throws when no key is configured. */
export function sealCredentials(
  orgId: number,
  integrationId: string,
  values: Record<string, string>,
  env: NodeJS.ProcessEnv = process.env,
): SealedCredentials {
  const k = credentialKeyState(env);
  if (!k.ok) throw new Error("credential_storage_disabled");
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", k.key, iv);
  cipher.setAAD(aad(orgId, integrationId, CREDENTIAL_KEY_VERSION));
  const ct = Buffer.concat([cipher.update(JSON.stringify(values), "utf8"), cipher.final()]);
  return {
    ciphertext: ct.toString("base64"),
    iv: iv.toString("base64"),
    authTag: cipher.getAuthTag().toString("base64"),
    keyVersion: CREDENTIAL_KEY_VERSION,
  };
}

/**
 * Decrypt a stored row. Throws when there is no key, the key changed, or the
 * row was tampered with / moved to another tenant (GCM authentication fails).
 */
export function decryptCredentialRow(
  row: Pick<OrgIntegrationCredential, "organizationId" | "integrationId" | "ciphertext" | "iv" | "authTag" | "keyVersion">,
  env: NodeJS.ProcessEnv = process.env,
): Record<string, string> {
  const k = credentialKeyState(env);
  if (!k.ok) throw new Error("credential_storage_disabled");
  if (row.keyVersion !== CREDENTIAL_KEY_VERSION) throw new Error("credential_key_version");
  const decipher = createDecipheriv("aes-256-gcm", k.key, Buffer.from(row.iv, "base64"));
  decipher.setAAD(aad(row.organizationId, row.integrationId, row.keyVersion));
  decipher.setAuthTag(Buffer.from(row.authTag, "base64"));
  const pt = Buffer.concat([decipher.update(Buffer.from(row.ciphertext, "base64")), decipher.final()]);
  const parsed = JSON.parse(pt.toString("utf8")) as unknown;
  if (!parsed || typeof parsed !== "object") throw new Error("credential_corrupt");
  const out: Record<string, string> = {};
  for (const [k2, v] of Object.entries(parsed as Record<string, unknown>)) if (typeof v === "string") out[k2] = v;
  return out;
}
