#!/usr/bin/env bash
# DocTurn — render /etc/docturn/docturn.env from AWS SSM Parameter Store.
#
#   sudo REGION=us-east-1 bash fetch-env-from-ssm.sh          # then: systemctl restart docturn
#
# Reads every parameter under /docturn/prod/ (SecureStrings decrypted via the
# instance role — see docs/AWS_DEPLOYMENT_RUNBOOK.md §5/§7), writes them as
# KEY="value" lines, appends the fixed production settings, and installs the
# file with mode 0640 root:docturn. Secrets therefore never pass through a
# shell prompt, git, or an AMI. Re-run whenever a parameter changes.
#
# Fails closed: if any REQUIRED variable is missing the file is NOT written and
# the service keeps its previous configuration (or refuses to start).
set -euo pipefail

SSM_PATH="${SSM_PATH:-/docturn/prod}"
OUT=/etc/docturn/docturn.env
SVC_USER=docturn
REQUIRED=(DATABASE_URL SESSION_SECRET PLATFORM_ADMIN_PASSWORD ATTACHMENT_KEY SYNTHETIC_DATA)

die() { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }
[[ $EUID -eq 0 ]] || die "run as root"
command -v aws >/dev/null || die "aws cli missing (bootstrap.sh installs it)"
command -v jq  >/dev/null || die "jq missing (bootstrap.sh installs it)"

# Region: explicit env, else the instance's own region from IMDSv2.
REGION="${REGION:-${AWS_DEFAULT_REGION:-}}"
if [[ -z "$REGION" ]]; then
  TOKEN=$(curl -sS -X PUT 'http://169.254.169.254/latest/api/token' \
            -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' || true)
  REGION=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" \
            'http://169.254.169.254/latest/meta-data/placement/region' || true)
fi
[[ -n "$REGION" ]] || die "could not determine region; set REGION=..."

echo "fetching $SSM_PATH/* from SSM ($REGION)"
JSON=$(aws ssm get-parameters-by-path --region "$REGION" --path "$SSM_PATH" \
         --recursive --with-decryption --output json) \
  || die "SSM read failed — check the instance role has ssm:GetParametersByPath + kms:Decrypt"

COUNT=$(jq '.Parameters | length' <<<"$JSON")
[[ "$COUNT" -gt 0 ]] || die "no parameters found under $SSM_PATH"

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
{
  echo "# Generated by fetch-env-from-ssm.sh from $SSM_PATH on $(date -u +%FT%TZ). Do not edit; re-run the script."
  # Each value is double-quoted with backslashes and quotes escaped, which is
  # the quoting systemd's EnvironmentFile understands.
  jq -r --arg p "$SSM_PATH/" '
    .Parameters[]
    | (.Name | sub("^" + $p; "")) as $k
    | select($k | test("^[A-Z][A-Z0-9_]*$"))
    | $k + "=\"" + (.Value | gsub("\\\\"; "\\\\") | gsub("\""; "\\\"")) + "\""
  ' <<<"$JSON"
  # Fixed production settings (documented in deploy/aws/docturn.env.example).
  echo 'NODE_ENV="production"'
  echo 'ATTACHMENT_STORE="fs-encrypted"'
  echo 'ATTACHMENT_DIR="/var/lib/docturn/attachments"'
} > "$TMP"

MISSING=()
for k in "${REQUIRED[@]}"; do
  grep -q "^$k=\"..*\"$" "$TMP" || MISSING+=("$k")
done
[[ ${#MISSING[@]} -eq 0 ]] || die "missing required parameter(s) under $SSM_PATH: ${MISSING[*]} — not writing $OUT"

# Guardrails that are cheap to check here and expensive to discover later.
if grep -q '^RATE_LIMIT="off"$' "$TMP"; then
  die "RATE_LIMIT=off is set in SSM — refusing to deploy with auth rate limiting disabled"
fi
# Proxy topology: Caddy on this host → the app must bind loopback (HOST unset)
# and trust only loopback (TRUST_PROXY unset). See docturn.env.example.
TP=$(sed -n 's/^TRUST_PROXY="\(.*\)"$/\1/p' "$TMP" | tr 'A-Z' 'a-z')
case "$TP" in
  0|false|off|no)
    die "TRUST_PROXY=$TP is set in SSM — behind Caddy every sign-in would be refused (insecure_transport). Delete the parameter (default: loopback)." ;;
  ""|1|true|on|yes|loopback) ;;
  *[!0-9]*) echo "WARNING: TRUST_PROXY=$TP — only needed for a proxy on ANOTHER host; Caddy here needs the default (unset)." >&2 ;;
  *) echo "WARNING: TRUST_PROXY=$TP is a hop count — any direct client could forge X-Forwarded-For. Delete the parameter (default: loopback)." >&2 ;;
esac
HOSTV=$(sed -n 's/^HOST="\(.*\)"$/\1/p' "$TMP")
if [[ -n "$HOSTV" && "$HOSTV" != "127.0.0.1" && "$HOSTV" != "::1" && "$HOSTV" != "localhost" ]]; then
  echo "WARNING: HOST=$HOSTV — the Node port will accept network connections directly, bypassing Caddy/TLS if the security group ever allows it. Delete the parameter (default: 127.0.0.1)." >&2
fi
if grep -q '^SYNTHETIC_DATA="true"$' "$TMP"; then
  echo "WARNING: SYNTHETIC_DATA=true — this instance will seed DEMO accounts. Fine for a test box, never for real PHI." >&2
fi
# Hospital integration credentials (Settings → Integrations) are encrypted with
# INTEGRATION_KEY; without a usable key the app refuses to store them.
IK=$(sed -n 's/^INTEGRATION_KEY="\(.*\)"$/\1/p' "$TMP")
if [[ -z "$IK" ]]; then
  echo "WARNING: INTEGRATION_KEY is not in SSM — hospitals cannot save Amion/Epic credentials (put /docturn/prod/INTEGRATION_KEY as a SecureString: openssl rand -hex 32)." >&2
elif [[ ! "$IK" =~ ^[0-9a-fA-F]{64}$ && ${#IK} -lt 32 ]]; then
  die "INTEGRATION_KEY must be 64 hex chars or at least 32 characters (openssl rand -hex 32)"
fi
PAP=$(sed -n 's/^PLATFORM_ADMIN_PASSWORD="\(.*\)"$/\1/p' "$TMP")
[[ ${#PAP} -ge 12 ]] || die "PLATFORM_ADMIN_PASSWORD is shorter than 12 chars — the app will refuse to create the operator account"

install -d -m 0750 -o root -g "$SVC_USER" /etc/docturn
install -m 0640 -o root -g "$SVC_USER" "$TMP" "$OUT"
echo "wrote $OUT ($(grep -c '=' "$OUT") variables, $COUNT from SSM). Next: systemctl restart docturn"
